<?php

return [
	'key' => 'group_5a08644ffa30ab99',
	'title' => 'Clock of Change options',
	'fields' => [
		[
			'key' => 'field_5a6e33a9036dsef3fa5',
			'label' => 'Your API Key',
			'name' => 'coc_api_key',
			'type' => 'text',
			'instructions' => 'your secret key to make calls to the coc api.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'your api key',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'maxlength' => 64,
		],
		[
			'key' => 'field_5a6e33a90ee6d66f3fa5',
			'label' => 'API base url',
			'name' => 'coc_api_url',
			'type' => 'text',
			'instructions' => 'the url to send requests to',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'your api url (without trailing slash)',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'maxlength' => 255,
		],
	],
	'location' => [
		[
			[
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'coc-settings',
			],
		],
	],
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
];